name: Init Dotnet Workflow
description: Initialize dotnet to version set in env variable
runs:
  using: composite
  steps:
    - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
