name: Contextive Docs
on:
  push:
    paths:
      - "docs/web/**"
      - ".github/workflows/contextive-docs.yml"
  # release:
  #   types: [published] #Temporary while debugging semantic release

# See https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings
# And https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  BRANCH_NAME: ${{ github.ref_name }}
  CONTEXTIVE_STAGE: ${{ github.event_name == 'release' && 'prod'                || 'test' }}
  AWS_ROLE: ${{ github.event_name == 'release'         && secrets.AWS_ROLE_PROD || secrets.AWS_ROLE_TEST }}
  AWS_REGION: ${{ github.event_name == 'release'       && 'eu-west-3'           || 'ap-southeast-2' }}

jobs:
  docs:
    name: Docs
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: "docs/web/"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: docs/web/package-lock.json

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}

      - run: npm ci

      - run: ./build-deploy-ci.sh
      - run: ./build-deploy-ci.sh
        env:
          CONTEXTIVE_ARCHIVE: 1
